### PR TITLE
Setup script

### PR DESCRIPTION
**Pull request by tammy**

### CODE REVIEW

**Comment by sadmansk** [comment]
@aneedalie is this only for mac or linux as well?

**Comment by sadmansk** [comment]
@aneedalie I'll do a run under cygwin and if it works there, it should work on Linux too

**Comment by tammy** [comment]
@sadmansk Theoretically it should work for anything that can run brew and terminal commands. I think. So anything Unix based?

**Comment by derekszen** [comment]
O hai. 

Looked over the script and tried running it. 
First of all, I ran it on a clean Ubuntu14.04, x64 box. 
The part that installs Homebrew is giving me an error: curl: (6) Could not resolve host. 
I can curl google.com perfectly fine though. 

Running through the official setup instructions at http://brew.sh/ gives me another error, telling me to install [LinuxBrew](https://github.com/Linuxbrew/linuxbrew). The "could not resolve host" error could totally be something from my end though. 

It would be best to have an option that doesn't require one to install Homebrew. Apt (or whatever your package manager may be) is powerful enough to install python 2.7.x and pip. 
Pip also has the functionality to install stuff from a [requirements file](https://pip.readthedocs.org/en/1.1/requirements.html).

**Comment by tammy** [comment]
Since we've dropped this direction, I'm just going to close the PR.

**Pull request closed without merging**
